# Generated by Django 4.1.9 on 2023-06-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mflixApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('email', models.CharField(max_length=100)),
                ('movie_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awards', models.JSONField()),
                ('cast', models.JSONField()),
                ('countries', models.JSONField()),
                ('directors', models.JSONField()),
                ('fullplot', models.TextField()),
                ('genres', models.JSONField()),
                ('imdb', models.JSONField()),
                ('languages', models.JSONField()),
                ('lastupdated', models.CharField(max_length=100)),
                ('metacritic', models.IntegerField()),
                ('num_mflix_comments', models.IntegerField()),
                ('plot', models.TextField()),
                ('poster', models.CharField(max_length=100)),
                ('rated', models.CharField(max_length=100)),
                ('released', models.DateTimeField()),
                ('runtime', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('tomatoes', models.JSONField()),
                ('type', models.CharField(max_length=100)),
                ('writers', models.JSONField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Theaters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('theaterId', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='People',
        ),
    ]
