# Generated by Django 4.1.9 on 2023-06-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('in_reply_to_status_id', models.CharField(max_length=255, null=True)),
                ('retweet_count', models.IntegerField(null=True)),
                ('contributors', models.CharField(max_length=255, null=True)),
                ('created_at', models.CharField(max_length=255)),
                ('geo', models.CharField(max_length=255, null=True)),
                ('source', models.CharField(max_length=255)),
                ('coordinates', models.CharField(max_length=255, null=True)),
                ('in_reply_to_screen_name', models.CharField(max_length=255, null=True)),
                ('truncated', models.BooleanField()),
                ('entities', models.JSONField()),
                ('retweeted', models.BooleanField()),
                ('place', models.CharField(max_length=255, null=True)),
                ('user', models.JSONField()),
                ('favorited', models.BooleanField()),
                ('in_reply_to_user_id', models.CharField(max_length=255, null=True)),
                ('id', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'db_tweet',
            },
        ),
    ]
