# Generated by Django 4.1.9 on 2023-06-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trcDjangoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='retweeted',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(db_index=True),
        ),
    ]
