# Generated by Django 2.2.8 on 2023-06-26 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Container',
            },
        ),
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.URLField()),
                ('view_count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'ShortURL',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Topic',
            },
        ),
        migrations.CreateModel(
            name='UserJSON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('registered', models.DateTimeField()),
                ('fullname', models.CharField(max_length=255)),
                ('icon', models.URLField()),
                ('profileviews', models.IntegerField()),
            ],
            options={
                'verbose_name': 'UserJSON',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('comments', models.IntegerField()),
                ('submit_date', models.DateTimeField()),
                ('promote_date', models.DateTimeField()),
                ('idJSON', models.CharField(max_length=255)),
                ('media', models.CharField(max_length=255)),
                ('diggs', models.IntegerField()),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('status', models.CharField(max_length=255)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.Container')),
                ('shorturl', models.ManyToManyField(to='stories.ShortURL')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.Topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.UserJSON')),
            ],
            options={
                'verbose_name': 'Story',
            },
        ),
    ]
