# Generated by Django 4.1.9 on 2023-06-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savedata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
