# Generated by Django 3.2.16 on 2023-06-25 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AirbnbBookingPortal', '0002_auto_20230626_0242'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='listingandreviews',
            table='airbnbbookingportal_listingandreviews',
        ),
    ]
