# Generated by Django 4.2.2 on 2023-06-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.IntegerField(primary_key=True, serialize=False)),
                ('limit', models.IntegerField()),
                ('products', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('birthdate', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField()),
                ('accounts', models.JSONField()),
                ('tier_and_details', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('transaction_count', models.IntegerField()),
                ('bucket_start_date', models.DateTimeField()),
                ('bucket_end_date', models.DateTimeField()),
                ('transactions', models.JSONField()),
            ],
        ),
    ]
