# Generated by Django 4.1.9 on 2023-06-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=255)),
                ('certificate_number', models.IntegerField()),
                ('business_name', models.CharField(max_length=255, null=True)),
                ('date', models.DateField()),
                ('result', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255, null=True)),
                ('address', models.JSONField()),
                ('city', models.CharField(max_length=255, null=True)),
                ('zip', models.IntegerField(null=True)),
                ('street', models.CharField(max_length=255, null=True)),
                ('number', models.IntegerField(null=True)),
            ],
        ),
    ]
