# Generated by Django 3.2.16 on 2023-06-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirbnbBookingPortal', '0004_auto_20230626_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingandreviews',
            name='accommodates',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listingandreviews',
            name='address',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='listingandreviews',
            name='amenities',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='listingandreviews',
            name='availability',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='listingandreviews',
            name='bathrooms',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='listingandreviews',
            name='bed_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listingandreviews',
            name='bedrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listingandreviews',
            name='beds',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listingandreviews',
            name='calendar_last_scraped',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='listingandreviews',
            name='cancellation_policy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listingandreviews',
            name='cleaning_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listingandreviews',
            name='extra_people',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listingandreviews',
            name='first_review',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='listingandreviews',
            name='guests_included',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listingandreviews',
            name='host',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='listingandreviews',
            name='house_rules',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='listingandreviews',
            name='images',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='listingandreviews',
            name='interaction',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='listingandreviews',
            name='last_review',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='listingandreviews',
            name='last_scraped',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='listingandreviews',
            name='maximum_nights',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listingandreviews',
            name='minimum_nights',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listingandreviews',
            name='number_of_reviews',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listingandreviews',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listingandreviews',
            name='property_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listingandreviews',
            name='review_scores',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='listingandreviews',
            name='reviews',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='listingandreviews',
            name='room_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listingandreviews',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
