# Generated by Django 2.2.8 on 2023-06-27 20:40

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('comments', models.IntegerField()),
                ('container', jsonfield.fields.JSONField()),
                ('submit_date', models.DateTimeField()),
                ('topic', jsonfield.fields.JSONField()),
                ('promote_date', models.DateTimeField()),
                ('idJSON', models.CharField(max_length=255)),
                ('media', models.CharField(max_length=255)),
                ('diggs', models.IntegerField()),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('user', jsonfield.fields.JSONField()),
                ('status', models.CharField(max_length=255)),
                ('shorturl', jsonfield.fields.JSONField()),
            ],
            options={
                'verbose_name': 'Story',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('technical_worker', 'Technical Worker'), ('senior_management', 'Senior Management')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
    ]
